# Error definitions for the Remotion Hybrid Pipeline Validation & Repair engine.

class ErrorCodes:
    # Parser layer
    PARSER_INVALID_OUTPUT = "PARSER_INVALID_OUTPUT"
    PARSER_EMPTY_INPUT = "PARSER_EMPTY_INPUT"
    
    # Planner & Marks Layer
    SCENE_PLAN_INVALID = "SCENE_PLAN_INVALID"
    MARKS_CONFLICT = "MARKS_CONFLICT"
    
    # Layout Layer
    LAYOUT_OVERFLOW = "LAYOUT_OVERFLOW"
    LAYOUT_NODE_MISSING = "LAYOUT_NODE_MISSING"
    
    # Motion Layer
    MOTION_TARGET_NOT_FOUND = "MOTION_TARGET_NOT_FOUND"
    MOTION_RANGE_INVALID = "MOTION_RANGE_INVALID"
    
    # DSL & Code Layer
    DSL_INVALID_COMPONENT = "DSL_INVALID_COMPONENT"
    CODE_RENDER_MISSING = "CODE_RENDER_MISSING"
    CODE_UNSAFE_API = "CODE_UNSAFE_API"
    CODE_SANDBOX_INCOMPATIBLE = "CODE_SANDBOX_INCOMPATIBLE"
    
    # System & Repair
    SCENE_REPAIR_EXHAUSTED = "SCENE_REPAIR_EXHAUSTED"
