import React, { useState } from 'react';
import { FileText, Layout, Palette, Code, Film, LayoutTemplate, ShieldCheck, Zap, MessageSquare, Activity, Eye, ChevronRight } from 'lucide-react';
import { useIdeStore } from '../../store/useIdeStore';

type TabType = 'script' | 'storyboard' | 'visual_strategy' | 'layout' | 'code';

interface TabConfig {
  id: TabType;
  label: string;
  icon: React.ReactNode;
  artifactType: string;
}

const TABS: TabConfig[] = [
  { id: 'script', label: '脚本', icon: <FileText className="h-4 w-4" />, artifactType: 'script' },
  { id: 'storyboard', label: '分镜', icon: <Film className="h-4 w-4" />, artifactType: 'storyboard' },
  { id: 'visual_strategy', label: '视觉策略', icon: <Palette className="h-4 w-4" />, artifactType: 'visual_strategy' },
  { id: 'layout', label: '场景布局', icon: <Layout className="h-4 w-4" />, artifactType: 'scene_layout_bundle' },
  { id: 'code', label: '场景代码', icon: <Code className="h-4 w-4" />, artifactType: 'scene_code' },
];

export const ArtifactTabs: React.FC = () => {
  const [activeTab, setActiveTab] = useState<TabType>('script');
  const artifactsByType = useIdeStore((s) => s.artifactsByType);
  const sceneCodeBySceneId = useIdeStore((s) => s.sceneCodeBySceneId);
  const scenes = useIdeStore((s) => s.scenes);

  const renderContent = () => {
    switch (activeTab) {
      case 'script': {
        const artifact = artifactsByType['script'];
        if (!artifact) {
          return <div className="text-sm text-gray-500">脚本尚未生成</div>;
        }
        return (
          <div className="space-y-2">
            <div className="text-xs text-gray-400">{artifact.summary}</div>
            <div className="rounded bg-gray-900 p-3 text-sm text-gray-200">
              {artifact.content_text || '无内容'}
            </div>
          </div>
        );
      }

      case 'storyboard': {
        const artifact = artifactsByType['storyboard'];
        if (!artifact) {
          return <div className="text-sm text-gray-500">分镜脚本尚未生成</div>;
        }
        const content = artifact.content_json as any;
        const scenes = content?.scenes || [];
        const validation = content?.validation || {};

        return (
          <div className="space-y-4">
            {/* 脚本质量反馈单 (Validation Feedback) */}
            {validation && (
              <div className="rounded border-2 border-gray-800 bg-gray-950 p-3 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                <div className="mb-3 flex items-center justify-between border-b border-gray-800 pb-2">
                  <div className="flex items-center gap-2">
                    <ShieldCheck className="h-4 w-4 text-emerald-400" />
                    <span className="text-xs font-bold text-gray-100 uppercase tracking-tighter">AI 脚本质量反馈单</span>
                  </div>
                  <div className="rounded bg-emerald-500/10 px-2 py-0.5 text-[9px] font-bold text-emerald-400">PASSED</div>
                </div>
                
                <div className="grid grid-cols-1 gap-2">
                  {[
                    { label: '语义覆盖度', value: validation.semantic_coverage, icon: <MessageSquare className="h-3 w-3" />, color: 'text-blue-400' },
                    { label: '视觉可实现性', value: validation.visual_feasibility, icon: <Eye className="h-3 w-3" />, color: 'text-purple-400' },
                    { label: '平台适配度', value: validation.platform_adaptability, icon: <Zap className="h-3 w-3" />, color: 'text-amber-400' },
                    { label: '叙事连续性', value: validation.narrative_continuity, icon: <ChevronRight className="h-3 w-3" />, color: 'text-emerald-400' },
                    { label: '情绪曲线符合度', value: validation.emotion_curve_compliance, icon: <Activity className="h-3 w-3" />, color: 'text-rose-400' },
                  ].map((item, i) => (
                    <div key={i} className="flex gap-2 rounded bg-gray-900/50 p-2 border border-gray-800/50">
                      <div className={`mt-0.5 ${item.color}`}>{item.icon}</div>
                      <div className="min-w-0 flex-1">
                        <div className="text-[10px] font-bold text-gray-500">{item.label}</div>
                        <div className="mt-0.5 text-[11px] leading-relaxed text-gray-300">{item.value || '评估中...'}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div className="text-xs text-gray-400">分镜详情清单 ({scenes.length})</div>
                <div className="text-[10px] text-gray-600">Generated by Director Agent</div>
              </div>
              {scenes.map((scene: any, idx: number) => (
                <div key={idx} className="rounded border border-gray-700 bg-gray-900 p-3">
                  <div className="mb-1 text-xs font-semibold text-violet-400">
                    场景 {scene.scene_id || idx + 1}
                  </div>
                  <div className="text-sm text-gray-300">{scene.script || '无脚本'}</div>
                  {scene.visual_design && (
                    <div className="mt-2 text-xs text-gray-500">
                      视觉设计: {scene.visual_design}
                    </div>
                  )}
                  {scene.layout_spec && (
                    <div className="mt-2 flex items-center gap-1 rounded bg-violet-500/10 px-2 py-1 text-violet-300 animate-pulse w-fit">
                      <LayoutTemplate className="h-3 w-3" />
                      <span className="text-[10px]">AI 布局已就绪</span>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        );
      }

      case 'visual_strategy': {
        const artifact = artifactsByType['visual_strategy'];
        if (!artifact) {
          return <div className="text-sm text-gray-500">视觉策略尚未生成</div>;
        }
        const content = artifact.content_json as any;
        return (
          <div className="space-y-3">
            <div className="text-xs text-gray-400">{artifact.summary}</div>
            <div className="rounded bg-gray-900 p-3">
              <div className="mb-2 text-sm font-semibold text-violet-400">风格家族</div>
              <div className="text-sm text-gray-300">{content?.style_family || '未知'}</div>
            </div>
            {content?.theme_profile && (
              <div className="rounded bg-gray-900 p-3">
                <div className="mb-2 text-sm font-semibold text-violet-400">主题配置</div>
                <div className="space-y-1 text-xs text-gray-400">
                  <div>主色: {content.theme_profile.primary_color || 'N/A'}</div>
                  <div>辅色: {content.theme_profile.secondary_color || 'N/A'}</div>
                  <div>背景: {content.theme_profile.background_color || 'N/A'}</div>
                </div>
              </div>
            )}
            {content?.llm_metadata && (
              <div className="rounded bg-gray-900 p-3">
                <div className="mb-2 text-sm font-semibold text-violet-400">生成信息</div>
                <div className="space-y-1 text-xs text-gray-400">
                  <div>风格来源: {content.llm_metadata.style_source}</div>
                  <div>主题来源: {content.llm_metadata.theme_source}</div>
                </div>
              </div>
            )}
          </div>
        );
      }

      case 'layout': {
        const layoutBundle = artifactsByType['scene_layout_bundle'];
        
        // 优先从全局 Bundle 读取，如果没有（即正在生成中），则从 scenes 列表提取实时同步的布局
        const sceneLayouts: Record<string, any> = layoutBundle?.content_json?.scene_layouts || {};
        
        // 补充从 scenes 实时同步过来的布局
        scenes.forEach(s => {
          if (s.layout_spec && !sceneLayouts[s.id]) {
            sceneLayouts[s.id] = s.layout_spec;
          }
        });

        const sceneIds = Object.keys(sceneLayouts);

        if (sceneIds.length === 0) {
          return <div className="text-sm text-gray-500 italic">正在等待场景布局优化 (SSE 实时同步)...</div>;
        }

        return (
          <div className="space-y-2">
            <div className="text-xs text-gray-400">
              {layoutBundle?.summary || `实时同步中 (${sceneIds.length} 个已就绪)`}
            </div>
            <div className="space-y-3">
              {sceneIds.map((sceneId) => {
                const layout = sceneLayouts[sceneId];
                return (
                  <div key={sceneId} className="rounded border border-gray-700 bg-gray-900 p-3">
                    <div className="mb-1 text-xs font-semibold text-violet-400">
                      场景 {sceneId}
                    </div>
                    <div className="space-y-1 text-xs text-gray-400">
                      <div className="font-mono text-[10px] opacity-70">
                        ELEMENTS: {layout.elements?.length || 0}
                      </div>
                      <div className="flex gap-2">
                        {layout.metadata?.layout_source && (
                          <span className="rounded bg-violet-900/30 px-1 text-[9px] text-violet-300">
                            {layout.metadata.layout_source}
                          </span>
                        )}
                        {layout.metadata?.intent_source && (
                          <span className="rounded bg-indigo-900/30 px-1 text-[9px] text-indigo-300">
                            {layout.metadata.intent_source}
                          </span>
                        )}
                      </div>
                      {layout.elements && (
                         <div className="mt-2 text-[10px] text-gray-500 border-t border-gray-800 pt-1">
                           {layout.elements.slice(0, 3).map((e: any) => e.primitive_type).join(', ')}
                           {layout.elements.length > 3 ? '...' : ''}
                         </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        );
      }

      case 'code': {
        const sceneIds = Object.keys(sceneCodeBySceneId);
        if (sceneIds.length === 0) {
          return <div className="text-sm text-gray-500">场景代码尚未生成</div>;
        }

        return (
          <div className="space-y-3">
            <div className="text-xs text-gray-400">
              已生成 {sceneIds.length} 个场景代码
            </div>
            {sceneIds.map((sceneId) => {
              const code = sceneCodeBySceneId[sceneId];
              return (
                <div key={sceneId} className="rounded border border-gray-700 bg-gray-900 p-3">
                  <div className="mb-2 text-xs font-semibold text-violet-400">
                    场景 {sceneId}
                  </div>
                  <pre className="max-h-40 overflow-auto text-xs text-gray-300">
                    {code || '无代码'}
                  </pre>
                </div>
              );
            })}
          </div>
        );
      }

      default:
        return null;
    }
  };

  const hasAnyArtifact = Object.keys(artifactsByType).length > 0 || Object.keys(sceneCodeBySceneId).length > 0;

  if (!hasAnyArtifact) {
    return null;
  }

  return (
    <div className="flex min-h-0 flex-col rounded-lg border border-gray-800 bg-[#1a1a1d]">
      <div className="flex flex-shrink-0 border-b border-gray-800">
        {TABS.map((tab) => {
          const hasData = tab.id === 'code'
            ? Object.keys(sceneCodeBySceneId).length > 0
            : !!artifactsByType[tab.artifactType];

          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              disabled={!hasData}
              className={`flex flex-1 items-center justify-center gap-1.5 px-3 py-2 text-xs font-medium transition-colors ${
                activeTab === tab.id
                  ? 'border-b-2 border-violet-500 text-violet-400'
                  : hasData
                  ? 'text-gray-400 hover:text-gray-300'
                  : 'cursor-not-allowed text-gray-600'
              }`}
            >
              {tab.icon}
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>
      <div className="min-h-0 flex-1 overflow-y-auto p-4">
        {renderContent()}
      </div>
    </div>
  );
};
